### ISSUE TITLE
tellstick.conf

### ISSUE THREAD

**Issue by burk80** [taskinen/home-assistant#1]
To make config easier and to not need to put an external volume to /etc/tellstick.conf .. 

why not make a ln -s to /config/tellstick.conf -> /etc/tellstick.conf ..

that way all the configs will be in the same external config..

just my two cents.. :)

apart from that .. so far everything is working fine.. :)

**Comment by taskinen** [comment]
Thank you for the suggestion! Indeed, getting rid of one external volume would simplify things.

But I am hesitant to break backwards compatibility with the change. Because that would require all previous users to change their systems to include the tellstick.conf file in their /config/ -mounted volume.

I will take a look next time I am making configuration changes to my environment if it could be done without breaking old installations.
