### ISSUE TITLE
tellstick duo on ubuntu 1804

### ISSUE THREAD

**Issue by jaromrax** [taskinen/home-assistant#3]
Hello,
  sorry for writing here, as it is not really an issue but a naive question:
- i've just found out that there will be no official support for ubuntu 1804
- i managed to run telldusd on VM (qemu+kvm) under ubuntu 1804 host, but it is not much convenient
- i see there exists A 'docker stuff' that I dont have any experience at all:

Is there possible - on my ubuntu 1804 host - run (the outdated 1604) telldusd and use my script (located /usr/local/share/teldus/scripts/rawdeviceevent/) ? Using your docker things? https://hub.docker.com/r/taskinen/home-assistant/

Thank you very much. I am really clueless about the powers of docker.
Jaromir

**Comment by taskinen** [comment]
Hi @jaromrax and thanks for your question!

Yes indeed! Docker allows you to run Docker containers in any host system you want regardles of the "operating system" inside the Docker image.

# Docker installation

Just download https://get.docker.com/ script and run it with root privileges on your server to install Docker daemon. You should also install `docker-compose` tool afterwards. Just download the Linux x64 binary from here into your system wide path: https://github.com/docker/compose/releases

# Your script

You could mount your script into the Docker container by adding one line to the Docker-compose example I have in the Docker hub page, for example:

```
...
volumes:
      - "./some/dir/config:/config"
      - "./some/dir/tellstick.conf:/etc/tellstick.conf"
      - "./some/dir/my_script.sh:/usr/local/share/teldus/scripts/rawdeviceevent/my_script.sh"
...
```

But since I am not familiar with your script, and how you would use it inside Home Assistant, I am not sure how it would work.

**Comment by jaromrax** [comment]
Thank you very much for the response. I will try to install it asap, but one thing worries me - [here](https://askubuntu.com/a/868755/539325) - I have seen that the docker has a 'remote' IP, while snap shares the IP. My script sends the information to localhost. I am curious how it will work. Jaromir

**Comment by taskinen** [comment]
@jaromrax The section in `docker-compose.yml`:

```
    ports:
      - "8123:8123"
```

Exposes the Home-Assistant container's web interface port 8123 also from your local machine's port 8123, so you can access it with your script from localhost or even from your local network. You can add more ports if needed.
