### ISSUE TITLE
HA 0.98

### ISSUE THREAD

**Issue by upsideduck** [taskinen/home-assistant#5]
I am somewhat ahead of the issue maybe but have you considered if it will be possible/feasible to bring Telldus support with v 0.98 as the official docker container will not use Debian going forward? I have tried to play around with this but my Docker skills are still quite lacking unfortunately.

**Comment by cartmanume** [comment]
`telldusd` seems to be in the official image already since it is shared with hass.io from now on. Left to do is to make it autostart, I started it manually from inside the container and the it worked. Maybe just install supervisord and the config for it will work as before? Maybe adapt the startup command for `hass` is needed in that file also.

**Comment by upsideduck** [comment]
@cartmanume That was great news! I set it up with supervisord to start both `hass` and `telldusd` and home assistant launches but my tellstick duo devices do not respond. Investigating a bit further (trying to start `telldusd` manually inside the container) I can see that it gets stuck at `telldusd daemon starting up` but it never connects to the physical device, even though the container is running in privilege mode. Do you manage to get the tellstick devices to respond?

**Comment by cartmanume** [comment]
Here is a snippet from my `docker-compose.yml`. I guess you need to forward the USB-devices to the container as well if you haven't already.
```
    volumes:
     ....
       - /etc/tellstick.conf:/etc/tellstick.conf
       - /dev/bus/usb:/dev/bus/usb:rw
    devices:
       - /dev/bus/usb:/dev/bus/usb:rwm
```
I will probably not dig into this more, found a Tellstick ZNet Lite v2 for a very good price yesterday and will migrate to that one now. :)

**Comment by upsideduck** [comment]
Tried without success unfortunately. Oh well, I will probably have to transfer it all over to Zigbee. I have a ZNet Lite v2 as well but I use 433MHz mostly for receiving signals (remote controls) and then the Znet is way to slow. Thanks for the suggestions though.

**Comment by taskinen** [comment]
Hi @upsideduck and @cartmanume!

I remade my image to be based on the latest official Docker base image, so now it is using Alpine Linux instead of Ubuntu. The telldusd was indeed already included in the official base image.

I reconfigured supervisord to start both, the Home Assistant and the telldusd, to the background.

The new image is available in Docker Hub as taskinen/home-assistant:latest
